name: 'Release Notifier'
description: 'Automatically comment on closed or fixed issues after a release is published.'
author: UGRC

branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  repo-token:
    description: 'A token with access to your repo (e.g. {{ secrets.GITHUB_TOKEN }})'
    required: true

runs:
  using: node20
  main: dist/index.js
